### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by gusmonod**
Fix typo in docs

### CODE REVIEW

**Comment by godlygeek** [comment]
There's at least 1 reference to "bbytearray" in the Comdb2 repo - https://github.com/bloomberg/comdb2/blob/be2bf2db2c4de7eea7407480c28700a81efda03c/tests/guid.test/runit#L477 - but it's in some commented out tests. It's possible that this message wouldn't match the error message reported by current Comdb2 versions. We should construct a test case reproducing this error, and check what the R7 error message is.

**Comment by gusmonod** [comment]
Closing in favor of #56

**Comment by godlygeek** [comment]
Hah! The error message coming from the DB itself _has_ changed since that documentation was written -- from "bbytearray" to "bytearray" 🤣 

I guess that was a typo in Comdb2 itself that has been fixed since we wrote the docs!

So, this PR _is_ actually correct, after all.

**Review by godlygeek — APPROVED** [review]
LGTM

**Pull request merged**
