### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kpfleming**

### CODE REVIEW

**Comment by godlygeek** [comment]
Would you mind amending with a Signed-Off-By in the commit message?

**Comment by kpfleming** [comment]
Doh! Before I do that, I'll enable the DCO bot on this repository and we'll see if it works properly.

**Comment by godlygeek** [comment]
@kpfleming Would you mind rebasing this on the latest master?

**Comment by godlygeek** [comment]
I was able to rebase this myself, actually - hooray github!

**Pull request merged**
